(function(){
  function rowSheet(name, headers, rows){return xs(name,[headers,...rows])}
  function cleanFile(s){return String(s||'').replace(/[\\/:*?"<>|]/g,'-').replace(/\s+/g,' ').trim()}
  function heDate(s){let a=String(s||'').slice(0,10).split('-');return a.length===3?a.reverse().join('.'):String(s||'')}
  function dl(name,sheets){saveXls(cleanFile(name),sheets)}
  function supplierName(id){return suppliers.find(s=>s.id===id)?.name||'ללא ספק'}
  function categoryName(id){return cats.find(c=>c.id===id)?.name||''}
  window.exportPurchasesSummary=function(){let rows=purchases.map(p=>[p.purchase_date,supplierName(p.supplier_id),p.invoice_number||'',p.payment_method||'',money(p.total_cost),p.notes||'']);dl('כל הרכישות '+heDate(new Date().toISOString().slice(0,10)),[rowSheet('היסטוריית רכישות',['תאריך','ספק','חשבונית','אופן תשלום','סה״כ','הערות'],rows)])}
  window.exportSinglePurchase=async function(id){try{let p=purchases.find(x=>x.id===id);if(!p)return;let source=(purchaseItems||[]).filter(i=>String(i.purchase_id)===String(id));if(!source.length){source=await req('/rest/v1/purchase_items?select=*&purchase_id=eq.'+encodeURIComponent(id)+'&order=created_at.asc')||[]}let productIds=[...new Set(source.map(i=>i.product_id).filter(Boolean))],missing=productIds.filter(pid=>!(prods||[]).some(x=>String(x.id)===String(pid)));if(missing.length){let extra=await req('/rest/v1/products?select=*&id=in.('+missing.map(encodeURIComponent).join(',')+')');if(Array.isArray(extra))extra.forEach(x=>{if(!(prods||[]).some(p=>String(p.id)===String(x.id)))prods.push(x)})}let items=source.map(i=>{let pr=(prods||[]).find(x=>String(x.id)===String(i.product_id));return[pr?.name||i.product_name||'מוצר',categoryName(pr?.category_id||i.category_id),i.quantity,money(i.unit_cost),money(i.line_total??Number(i.quantity)*Number(i.unit_cost)),money(i.sale_price??pr?.price??0)]});let meta=[['פרט','ערך'],['תאריך',p.purchase_date],['ספק',supplierName(p.supplier_id)],['חשבונית',p.invoice_number||''],['אופן תשלום',p.payment_method||''],['סה״כ',money(p.total_cost)+' ₪'],['הערות',p.notes||'']];dl('רכישה '+supplierName(p.supplier_id)+' '+heDate(p.purchase_date)+(p.invoice_number?' חשבונית '+p.invoice_number:''),[xs('פרטי רכישה',meta),rowSheet('מוצרים ברכישה',['מוצר','קטגוריה','כמות','מחיר קנייה','סה״כ','מחיר מכירה'],items)])}catch(e){alert('הורדת הרכישה נכשלה: '+(e.message||e))}}
  window.exportProductsAll=function(){let rows=activeProducts().map(p=>[p.name,categoryName(p.category_id),money(p.price),p.stock_quantity,p.low_stock_threshold,money(p.last_purchase_price),money(p.average_cost)]);dl('כל המוצרים '+heDate(new Date().toISOString().slice(0,10)),[rowSheet('כל המוצרים',['מוצר','קטגוריה','מחיר מכירה','מלאי','התראת מלאי','מחיר קנייה אחרון','עלות ממוצעת'],rows)])}
  window.exportProductsCategory=function(catId){let c=cats.find(x=>x.id===catId);let rows=activeProducts().filter(p=>p.category_id===catId).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)).map(p=>[p.name,money(p.price),p.stock_quantity,p.low_stock_threshold,money(p.last_purchase_price),money(p.average_cost)]);dl('מוצרים '+(c?.name||'קטגוריה')+' '+heDate(new Date().toISOString().slice(0,10)),[rowSheet(c?.name||'קטגוריה',['מוצר','מחיר מכירה','מלאי','התראת מלאי','מחיר קנייה אחרון','עלות ממוצעת'],rows)])}
  window.exportSuppliersVisible=function(){let rows=suppliers.map(s=>[s.name,s.phone||'',s.email||'',s.payment_terms||'',s.notes||'']);dl('רשימת ספקים '+heDate(new Date().toISOString().slice(0,10)),[rowSheet('ספקים',['שם ספק','טלפון','מייל','תנאי תשלום','הערות'],rows)])}
  window.exportInventoryVisible=function(){let rows=(inventoryMovements||[]).map(m=>[new Date(m.created_at).toLocaleString('he-IL'),m.product_name,m.change_qty,m.reason,m.note||'']);dl('היסטוריית מלאי '+heDate(new Date().toISOString().slice(0,10)),[rowSheet('התאמות מלאי',['תאריך ושעה','מוצר','שינוי כמות','סיבה','הערה'],rows)])}
  window.exportFeedbackVisible=async function(){try{let rows=await req('/rest/v1/customer_feedback?select=*&order=created_at.desc');dl('הודעות לקוחות '+heDate(new Date().toISOString().slice(0,10)),[rowSheet('הודעות לקוחות',['תאריך ושעה','סטטוס','הודעה'],rows.map(r=>[new Date(r.created_at).toLocaleString('he-IL'),r.is_read?'נקרא':'חדש',r.message]))])}catch(e){alert('הורדת Excel נכשלה: '+e.message)}}
  function addButton(parent,id,text,fn,cls='light'){if(!parent||document.getElementById(id))return;let b=document.createElement('button');b.id=id;b.className=cls;b.type='button';b.textContent=text;b.onclick=fn;parent.appendChild(b)}
  function enhanceHistory(){let tab=$('historyTab');if(!tab)return;let bar=tab.querySelector('.bar');addButton(bar,'excelPurchasesSummary','Excel – כל הרכישות',exportPurchasesSummary);tab.querySelectorAll('.history-card').forEach((card,idx)=>{let p=purchases[idx];if(!p||!openPurchases.has(p.id))return;let actions=card.querySelector('.history-body .row-actions');addButton(actions,'excelPurchase_'+p.id,'Excel – רכישה זו',()=>exportSinglePurchase(p.id),'green')})}
  function enhanceProducts(){let tab=$('productsTab');if(!tab)return;let h=tab.querySelector('.card h3');let bar=h?.parentElement?.classList.contains('bar')?h.parentElement:null;if(!bar){bar=document.createElement('div');bar.className='bar';if(h){h.parentNode.insertBefore(bar,h);bar.appendChild(h)}}addButton(bar,'excelProductsAll','Excel – כל המוצרים',exportProductsAll);tab.querySelectorAll('.cat-admin').forEach((box,idx)=>{let cat=cats[idx];if(!cat||!openCats.has(cat.id))return;let body=box.querySelector('.cat-body');if(!body)return;let tools=body.querySelector('.category-excel-tools');if(!tools){tools=document.createElement('div');tools.className='row-actions category-excel-tools';tools.style.margin='8px 0';body.prepend(tools)}addButton(tools,'excelCat_'+cat.id,'Excel – קטגוריה זו',()=>exportProductsCategory(cat.id),'light')})}
  function enhanceStock(){let tab=$('stockTab');let bar=tab?.querySelector('.card:nth-child(2) .bar');addButton(bar,'excelInventoryVisible','Excel – ההיסטוריה המוצגת',exportInventoryVisible)}
  function enhanceSuppliers(){let modal=$('supplierModal');let bar=modal?.querySelector('.bar');addButton(bar,'excelSuppliersVisible','Excel – ספקים',exportSuppliersVisible)}
  function enhanceFeedback(){let tab=$('feedbackTab');let bar=tab?.querySelector('.bar');addButton(bar,'excelFeedbackVisible','Excel – הודעות',exportFeedbackVisible)}
  function enhanceReports(){let tab=$('reportTab');let bar=tab?.querySelector('.bar');if(bar&&!document.getElementById('excelCurrentReport')){let b=document.createElement('button');b.id='excelCurrentReport';b.className='light';b.textContent='Excel – הדוח המוצג';b.onclick=()=>{if(typeof exportSalesReportExcel==='function')exportSalesReportExcel();else if(typeof exportReportExcel==='function')exportReportExcel()};bar.appendChild(b)}}
  function run(){enhanceHistory();enhanceProducts();enhanceStock();enhanceSuppliers();enhanceFeedback();enhanceReports()}
  function wrap(name){let old=window[name];if(typeof old!=='function'||old.__excelWrapped)return;let f=function(){let r=old.apply(this,arguments);Promise.resolve(r).finally(()=>setTimeout(run,0));return r};f.__excelWrapped=true;window[name]=f}
  ['renderPurchaseHistory','renderAdmin','renderInventoryHistory','renderSupplierManager','loadFeedbackAdmin','adminTab'].forEach(wrap);
  window.addEventListener('load',()=>setTimeout(run,0));setTimeout(run,500);
})();