// Offline-first data cache and durable automatic sync for store management.
(function(){
'use strict';
const DB='simple-store-offline',VER=2,CP='/rest/v1/products?select=*&order=category_id.asc,sort_order.asc,created_at.asc',CC='/rest/v1/categories?select=*&order=sort_order.asc';let dp=null,syncing=false,retry=null;
function db(){if(dp)return dp;dp=new Promise((ok,no)=>{let r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{let d=r.result;if(!d.objectStoreNames.contains('responses'))d.createObjectStore('responses');if(!d.objectStoreNames.contains('operations'))d.createObjectStore('operations',{keyPath:'id'});if(!d.objectStoreNames.contains('meta'))d.createObjectStore('meta')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});return dp}
async function get(s,k){let d=await db();return new Promise((ok,no)=>{let r=d.transaction(s).objectStore(s).get(k);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}async function put(s,v,k){let d=await db();return new Promise((ok,no)=>{let t=d.transaction(s,'readwrite'),o=t.objectStore(s);k===undefined?o.put(v):o.put(v,k);t.oncomplete=ok;t.onerror=()=>no(t.error)})}async function del(s,k){let d=await db();return new Promise((ok,no)=>{let t=d.transaction(s,'readwrite');t.objectStore(s).delete(k);t.oncomplete=ok;t.onerror=()=>no(t.error)})}async function all(s){let d=await db();return new Promise((ok,no)=>{let r=d.transaction(s).objectStore(s).getAll();r.onsuccess=()=>ok(r.result||[]);r.onerror=()=>no(r.error)})}
const method=o=>String(o?.method||'GET').toUpperCase();function body(o){try{return typeof o.body==='string'?JSON.parse(o.body):o.body||null}catch(e){return null}}function opts(o){let c={method:method(o),headers:Object.assign({},o?.headers||{})};if(o?.body!==undefined)c.body=o.body;delete c.headers.Authorization;delete c.headers.apikey;return c}function fid(p){let m=p.match(/[?&]id=eq\.([^&]+)/);return m?decodeURIComponent(m[1]):null}async function cache(p,d){await put('responses',{data:d,savedAt:Date.now()},p)}async function cached(p){let x=await get('responses',p);return x?.data}async function ops(){return(await all('operations')).sort((a,b)=>a.createdAt-b.createdAt)}
function bar(){let b=document.getElementById('offlineStatus');if(b)return b;let s=document.createElement('style');s.textContent='#offlineStatus{position:sticky;top:0;z-index:9999;padding:7px 12px;text-align:center;font-weight:800;background:#dcfce7;color:#166534}#offlineStatus.offline{background:#fef3c7;color:#92400e}#offlineStatus.pending{background:#dbeafe;color:#1e40af}#offlineStatus button{margin-inline-start:8px;min-height:32px!important;padding:4px 9px!important}';document.head.appendChild(s);b=document.createElement('div');b.id='offlineStatus';document.body.prepend(b);return b}async function status(){let n=(await ops()).length,b=bar(),last=await get('meta','lastSync');b.className=!navigator.onLine?'offline':n?'pending':'';b.innerHTML=!navigator.onLine?'אין אינטרנט · אפשר להמשיך לעבוד · '+n+' שינויים ממתינים':n?'מחובר · מסנכרן '+n+' שינויים... <button onclick="syncOfflineChanges(true)">סנכרן עכשיו</button>':'מחובר · מסונכרן'+(last?' · '+new Date(last).toLocaleTimeString('he-IL',{hour:'2-digit',minute:'2-digit'}):'')}
async function queue(p,o){let x={id:crypto.randomUUID(),path:p,options:opts(o),createdAt:Date.now()};await put('operations',x);return x}
async function optimistic(x){let b=body(x.options)||{},m=method(x.options),r=null;if(x.path.startsWith('/rest/v1/products')){if(m==='POST'){let row=Object.assign({id:b.id||crypto.randomUUID(),created_at:new Date().toISOString()},b);b.id=row.id;x.options.body=JSON.stringify(b);await put('operations',x);prods.push(row);r=[row]}else if(m==='PATCH'){let id=fid(x.path);prods=prods.map(i=>String(i.id)===String(id)?Object.assign({},i,b):i)}await cache(CP,prods)}if(x.path.startsWith('/rest/v1/categories')){if(m==='POST'){let row=Object.assign({id:b.id||crypto.randomUUID()},b);b.id=row.id;x.options.body=JSON.stringify(b);await put('operations',x);cats.push(row);r=[row]}else if(m==='PATCH'){let id=fid(x.path);cats=cats.map(i=>String(i.id)===String(id)?Object.assign({},i,b):i)}await cache(CC,cats)}if(x.path==='/rest/v1/rpc/adjust_stock'){prods=prods.map(i=>String(i.id)===String(b.p_product_id)?Object.assign({},i,{stock_quantity:Number(i.stock_quantity||0)+Number(b.p_change_qty||0)}):i);await cache(CP,prods)}if(x.path==='/rest/v1/rpc/create_purchase'){for(let l of b.p_items||[])prods=prods.map(i=>String(i.id)===String(l.product_id)?Object.assign({},i,{stock_quantity:Number(i.stock_quantity||0)+Number(l.quantity||0),price:Number(l.sale_price==null?i.price:l.sale_price)}):i);await cache(CP,prods)}try{renderCats();renderSelects();renderAdmin();renderCategoryManager();fillStockCategories()}catch(e){}return r}
const net=window.req;window.req=async function(p,o={}){if(method(o)==='GET'){try{let d=await net(p,o);await cache(p,d);return d}catch(e){let c=await cached(p);if(c!==undefined)return c;throw e}}if(!navigator.onLine){let x=await queue(p,o),r=await optimistic(x);await status();return r}try{return await net(p,o)}catch(e){let x=await queue(p,o),r=await optimistic(x);await status();schedule();return r}};
const upload=window.uploadImage;if(upload)window.uploadImage=async function(f,p){if(f&&!navigator.onLine)throw new Error('העלאת תמונה דורשת אינטרנט. אפשר להמשיך בשאר העבודה.');return upload(f,p)};
function schedule(ms=4000){clearTimeout(retry);retry=setTimeout(()=>sync(false),ms)}async function sync(force){if(syncing||!navigator.onLine)return;let pending=await ops();if(!pending.length){await status();return}syncing=true;await status();try{for(let x of pending){await net(x.path,x.options);await del('operations',x.id)}await put('meta',Date.now(),'lastSync');try{await load();if(typeof admin!=='undefined'&&admin&&typeof loadAdminData==='function')await loadAdminData()}catch(e){}if(force)alert('כל העדכונים הועלו לענן בהצלחה')}catch(e){schedule(10000)}finally{syncing=false;await status()}}
window.syncOfflineChanges=sync;window.addEventListener('offline',status);window.addEventListener('online',()=>{status();schedule(700)});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&navigator.onLine)schedule(500)});setInterval(()=>{if(navigator.onLine)sync(false)},30000);status().then(()=>{if(navigator.onLine)schedule(1000)}).catch(console.error);
})();