// Manual special sales: cost-price / discounted sales.
(function(){
function cost(p){let a=Number(p?.average_cost||0),l=Number(p?.last_purchase_price||0);return a>0?a:l}
function products(){return prods.filter(p=>p.is_active!==false).sort((a,b)=>String(a.name).localeCompare(String(b.name),'he'))}
function find(name){let n=String(name||'').trim().toLocaleLowerCase('he');return products().find(p=>String(p.name||'').trim().toLocaleLowerCase('he')===n)}
function ensure(){let menu=document.querySelector('#admin .adminmenu');if(!menu||document.getElementById('specialSaleTab'))return;menu.insertAdjacentHTML('beforeend','<button class="green" onclick="adminTab(\'specialSaleTab\');renderSpecialSale()">מכירה מיוחדת</button>');document.getElementById('admin').insertAdjacentHTML('beforeend','<div class="adminTab hidden" id="specialSaleTab"><div class="card form"><h3>מכירה מיוחדת</h3><div class="msg">לרישום מוצר שנמכר במחיר עלות או בהנחה. המכירה תופיע בסיכום המכירות ותופחת מהמלאי.</div><label>מוצר</label><input id="specialSaleProduct" list="specialSaleProducts" autocomplete="off" placeholder="הקלד או בחר מוצר" oninput="specialSaleCalc()"><datalist id="specialSaleProducts"></datalist><div id="specialSaleInfo" class="msg"></div><label>סוג מכירה</label><select id="specialSaleType" onchange="specialSaleTypeChanged()"><option value="cost">מחיר עלות</option><option value="discount">מחיר בהנחה</option></select><label>כמות</label><input id="specialSaleQty" type="number" min="1" step="1" value="1" oninput="specialSaleCalc()"><label>מחיר מכירה ליחידה</label><input id="specialSalePrice" type="number" min="0" step="0.01" oninput="specialSaleCalc()"><div class="grand-total">סה״כ מכירה: <span id="specialSaleTotal">0.00</span> ₪</div><label>הערה</label><textarea id="specialSaleNote"></textarea><button class="green" style="width:100%" onclick="saveSpecialSale()">שמור מכירה והפחת מהמלאי</button></div></div>')}
window.renderSpecialSale=function(){ensure();document.getElementById('specialSaleProducts').innerHTML=products().map(p=>'<option value="'+esc(p.name)+'"></option>').join('');specialSaleCalc()};
window.specialSaleTypeChanged=function(){let p=find(document.getElementById('specialSaleProduct').value);if(document.getElementById('specialSaleType').value==='cost'&&p)document.getElementById('specialSalePrice').value=cost(p).toFixed(2);specialSaleCalc()};
window.specialSaleCalc=function(){let p=find(document.getElementById('specialSaleProduct')?.value),q=Math.max(1,Number(document.getElementById('specialSaleQty')?.value||1)),price=Number(document.getElementById('specialSalePrice')?.value||0);if(p&&document.getElementById('specialSaleType')?.value==='cost'&&!document.getElementById('specialSalePrice').value)document.getElementById('specialSalePrice').value=cost(p).toFixed(2);let info=document.getElementById('specialSaleInfo');if(info)info.textContent=p?'מלאי: '+Number(p.stock_quantity||0)+' | עלות: '+money(cost(p))+' ₪':'יש לבחור מוצר קיים';let t=document.getElementById('specialSaleTotal');if(t)t.textContent=money(q*Number(document.getElementById('specialSalePrice')?.value||price))};
window.saveSpecialSale=async function(){try{let p=find(document.getElementById('specialSaleProduct').value),q=Math.max(1,parseInt(document.getElementById('specialSaleQty').value||1)),type=document.getElementById('specialSaleType').value,price=Number(document.getElementById('specialSalePrice').value);if(!p)return alert('יש לבחור מוצר קיים');if(q>Number(p.stock_quantity||0))return alert('אין מספיק מלאי');if(!Number.isFinite(price)||price<0)return alert('יש להזין מחיר מכירה');let label=type==='cost'?'מחיר עלות':'מחיר בהנחה';if(!confirm('לשמור מכירה של '+p.name+' × '+q+' ב'+label+'?\nסה״כ: '+money(price*q)+' ₪\nהמלאי יופחת בהתאם.'))return;await req('/rest/v1/rpc/create_manual_product_sale',{method:'POST',body:JSON.stringify({p_product_id:p.id,p_quantity:q,p_sale_type:type,p_unit_sale_price:price,p_note:document.getElementById('specialSaleNote').value||null,p_sold_at:new Date().toISOString()})});await load();document.getElementById('specialSaleProduct').value='';document.getElementById('specialSaleQty').value='1';document.getElementById('specialSalePrice').value='';document.getElementById('specialSaleNote').value='';specialSaleCalc();alert('המכירה נשמרה, המלאי עודכן והיא תופיע בסיכום המכירות')}catch(e){alert('שמירת המכירה נכשלה: '+e.message)}};
window.ensureSpecialSales=ensure;
})();