(function(){
 const STORAGE='store_gpt_messages_v1';let messages=[],proposal=null,lastUpgrade=null,pendingActions=[];
 try{messages=JSON.parse(localStorage.getItem(STORAGE)||'[]');if(!Array.isArray(messages))messages=[]}catch{messages=[]}
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
 function save(){localStorage.setItem(STORAGE,JSON.stringify(messages.slice(-40)))}
 function ensure(){if(document.getElementById('storeGptTab'))return;const menu=document.querySelector('#admin .adminmenu'),tabs=document.querySelector('#admin');if(!menu||!tabs)return;const btn=document.createElement('button');btn.className='blue';btn.textContent='GPT';btn.onclick=()=>{adminTab('storeGptTab');render()};menu.appendChild(btn);const section=document.createElement('div');section.className='adminTab hidden';section.id='storeGptTab';section.innerHTML='<div class="card" style="max-width:1050px;margin:auto"><div class="bar"><div><h3 style="margin:0">GPT</h3><div class="msg">עוזר מנהל חכם — שיחה, אינטרנט, נתוני החנות ושינויים באישור</div></div><button class="light" id="storeGptNew">שיחה חדשה</button></div><div id="storeGptMessages" style="height:min(48vh,560px);overflow:auto;padding:12px;background:#f8fafc;border-radius:14px;margin:14px 0"></div><div id="storeGptActions"></div><div id="storeGptProposal"></div><div id="storeGptReview"></div><div class="form"><textarea id="storeGptInput" rows="3" placeholder="שאל שאלה, בקש לבדוק מלאי/מחירים, או בקש שינוי בחנות..." style="resize:vertical"></textarea><div class="bar" style="flex-wrap:wrap"><label style="display:flex;gap:7px;align-items:center;margin:0"><input id="storeGptWeb" type="checkbox" checked style="width:auto;margin:0"> חיפוש באינטרנט</label><div style="display:flex;gap:8px"><button class="light" id="storeGptPlan">שינוי בקוד האתר</button><button class="blue" id="storeGptSend">שלח</button></div></div><div class="msg" id="storeGptStatus"></div></div></div>';tabs.appendChild(section);section.querySelector('#storeGptNew').onclick=()=>{if(messages.length&&!confirm('לפתוח שיחה חדשה?'))return;messages=[];proposal=null;lastUpgrade=null;pendingActions=[];save();render();renderActions();renderProposal();renderReview(null)};section.querySelector('#storeGptSend').onclick=send;section.querySelector('#storeGptPlan').onclick=proposeUpgrade;section.querySelector('#storeGptInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});render();renderActions();renderProposal()}
 function render(){const box=document.getElementById('storeGptMessages');if(!box)return;if(!messages.length)box.innerHTML='<div class="msg" style="text-align:center;padding:45px 10px">איך אפשר לעזור? אפשר לשאול גם על מוצרים, מחירים, מלאי וספקים.</div>';else box.innerHTML=messages.map(m=>'<div style="display:flex;justify-content:'+(m.role==='user'?'flex-start':'flex-end')+';margin:10px 0"><div style="max-width:82%;white-space:pre-wrap;line-height:1.55;padding:11px 14px;border-radius:14px;background:'+(m.role==='user'?'#dbeafe':'#fff')+';box-shadow:0 1px 3px #0001">'+esc(m.content)+'</div></div>').join('');box.scrollTop=box.scrollHeight}
 function actionLabel(a){if(a.action==='adjust_stock')return 'עדכון מלאי: '+(a.change_qty>0?'+':'')+a.change_qty+' למוצר '+(a.product_id||'');const t={create:'הוספה',update:'עדכון',deactivate:'השבתה'}[a.action]||a.action;return t+' '+({product:'מוצר',category:'קטגוריה',supplier:'ספק'}[a.entity]||a.entity)+(a.data?.name?' — '+a.data.name:'')}
 function renderActions(){const box=document.getElementById('storeGptActions');if(!box)return;if(!pendingActions.length){box.innerHTML='';return}box.innerHTML='<div class="card" style="margin:10px 0;border:2px solid #10b981"><h3 style="margin-top:0">פעולות בחנות ממתינות לאישור</h3><ul>'+pendingActions.map(a=>'<li>'+esc(actionLabel(a))+'</li>').join('')+'</ul><div class="bar"><span class="msg">שום שינוי לא יבוצע בלי אישור שלך.</span><button class="green" id="storeGptApplyActions">אשר ובצע</button></div><div class="msg" id="storeGptActionStatus"></div></div>';document.getElementById('storeGptApplyActions').onclick=applyStoreActions}
 async function applyStoreActions(){const b=document.getElementById('storeGptApplyActions'),s=document.getElementById('storeGptActionStatus');if(!pendingActions.length||b?.disabled)return;if(!confirm('לבצע עכשיו את הפעולות המפורטות בנתוני החנות?'))return;b.disabled=true;s.textContent='מבצע...';try{await api('/api/gpt-store-action',{actions:pendingActions});pendingActions=[];renderActions();await load();await loadAdminData();messages.push({role:'assistant',content:'הפעולות אושרו ובוצעו בנתוני החנות.'});save();render()}catch(e){s.textContent='שגיאה: '+e.message;b.disabled=false}}
 function renderProposal(){const box=document.getElementById('storeGptProposal');if(!box)return;if(!proposal){box.innerHTML='';return}const files=(proposal.files||[]).map(x=>'<code>'+esc(x)+'</code>').join(' '),steps=(proposal.steps||[]).map(x=>'<li>'+esc(x)+'</li>').join('');box.innerHTML='<div class="card" style="margin:10px 0;border:2px solid #dbeafe"><h3 style="margin-top:0">שדרוג קוד מוכן לאישור: '+esc(proposal.title||'שינוי באתר')+'</h3><p>'+esc(proposal.summary||'')+'</p><div class="msg"><b>קבצים צפויים:</b> '+files+'</div><ol>'+steps+'</ol><div class="bar"><span class="msg">רמת סיכון: '+esc(proposal.risk||'')+'</span><button class="blue" id="storeGptApprove">אשר והכן לבדיקה</button></div><div class="msg" id="storeGptApplyStatus">האתר הפעיל לא ישתנה עד לפרסום.</div></div>';document.getElementById('storeGptApprove').onclick=applyUpgrade}
 async function api(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'שגיאה');return d}
 async function applyUpgrade(){const button=document.getElementById('storeGptApprove'),status=document.getElementById('storeGptApplyStatus');if(!proposal||button?.disabled)return;if(!confirm('להכין את שינויי הקוד לבדיקה?'))return;button.disabled=true;status.textContent='מכין קוד לבדיקה...';try{const d=await api('/api/gpt-apply',{proposal});lastUpgrade=d;await loadReview(d.prNumber);button.textContent='הוכן לבדיקה'}catch(e){status.textContent='שגיאה: '+e.message;button.disabled=false}}
 async function loadReview(n){const box=document.getElementById('storeGptReview');box.innerHTML='<div class="msg">טוען פירוט שינויים...</div>';try{const d=await api('/api/gpt-review',{prNumber:n});renderReview(d)}catch(e){box.innerHTML='<div class="msg">שגיאה בטעינת הבדיקה: '+esc(e.message)+'</div>'}}
 function renderReview(d){const box=document.getElementById('storeGptReview');if(!box)return;if(!d){box.innerHTML='';return}const files=(d.files||[]).map(f=>'<details><summary><b>'+esc(f.filename)+'</b> — +'+f.additions+' / -'+f.deletions+'</summary><pre dir="ltr" style="text-align:left;white-space:pre-wrap;max-height:360px;overflow:auto;background:#111827;color:#f9fafb;padding:12px;border-radius:10px">'+esc(f.patch||'אין diff')+'</pre></details>').join('');box.innerHTML='<div class="card" style="border:2px solid #f59e0b"><h3>בדיקה לפני פרסום</h3>'+files+'<div class="bar"><button class="light" id="storeGptCancel">בטל</button><button class="blue" id="storeGptPublish">פרסם באתר הפעיל</button></div><div class="msg" id="storeGptPublishStatus"></div></div>';document.getElementById('storeGptPublish').onclick=()=>publishUpgrade(d.prNumber);document.getElementById('storeGptCancel').onclick=()=>cancelUpgrade(d.prNumber)}
 async function publishUpgrade(n){const s=document.getElementById('storeGptPublishStatus'),b=document.getElementById('storeGptPublish');if(!confirm('לפרסם את השדרוג באתר הפעיל?'))return;b.disabled=true;s.textContent='מפרסם...';try{await api('/api/gpt-publish',{prNumber:n});s.textContent='פורסם ל-main ונשלח לפריסה.';b.textContent='פורסם'}catch(e){s.textContent='שגיאה: '+e.message;b.disabled=false}}
 async function cancelUpgrade(n){const s=document.getElementById('storeGptPublishStatus'),b=document.getElementById('storeGptCancel');if(!confirm('לבטל את השדרוג?'))return;b.disabled=true;try{await api('/api/gpt-cancel',{prNumber:n});s.textContent='השדרוג בוטל.';document.getElementById('storeGptPublish').disabled=true}catch(e){s.textContent='שגיאה: '+e.message;b.disabled=false}}
 async function proposeUpgrade(){const input=document.getElementById('storeGptInput'),status=document.getElementById('storeGptStatus'),button=document.getElementById('storeGptPlan'),request=input?.value.trim();if(!request||button?.disabled)return;button.disabled=true;status.textContent='בודק את האתר ומכין הצעת שדרוג...';try{const d=await api('/api/gpt-propose',{request});proposal=d.proposal;renderProposal();renderReview(null);status.textContent='ההצעה מוכנה.'}catch(e){status.textContent='שגיאה: '+e.message}finally{button.disabled=false}}
 async function send(){const input=document.getElementById('storeGptInput'),status=document.getElementById('storeGptStatus'),button=document.getElementById('storeGptSend'),text=input?.value.trim();if(!text||button?.disabled)return;messages.push({role:'user',content:text});input.value='';save();render();button.disabled=true;status.textContent='GPT חושב ובודק את נתוני החנות...';try{const d=await api('/api/gpt',{messages:messages.slice(-40),webSearch:!!document.getElementById('storeGptWeb')?.checked});messages.push({role:'assistant',content:d.text||'לא התקבלה תשובה'});pendingActions=Array.isArray(d.actions)?d.actions:[];save();render();renderActions();status.textContent=''}catch(e){status.textContent='שגיאה: '+e.message}finally{button.disabled=false;input.focus()}}
 window.ensureStoreGpt=ensure;
})();