let storefrontDesign={store_name:'מערכת מכירה',logo_url:'',primary_color:'#2563eb',accent_color:'#16a34a',banner_style:'soft',show_search:true,low_stock_message:true,feedback_email:''};window.storefrontDesign=storefrontDesign;
function ensureStorefrontModernUI(){let home=$('home');if(!home)return;document.body.classList.add('modern-storefront');let title=document.querySelector('.top>b');if(title)title.id='storeBrandName';if(!$('storeSearch')){let wrap=document.createElement('div');wrap.id='storeSearchWrap';wrap.className='store-search';wrap.innerHTML='<span>⌕</span><input id="storeSearch" placeholder="חיפוש מוצר..." autocomplete="off"><button type="button" class="light" onclick="clearStoreSearch()">×</button>';let cats=$('categories');cats?.parentElement.insertBefore(wrap,cats);$('storeSearch').addEventListener('input',renderStoreSearch)}enhanceCartBar();ensureDesignAdmin();loadStorefrontDesign()}
async function loadStorefrontDesign(){try{let rows=await req('/rest/v1/storefront_design_settings?id=eq.1&select=*');if(rows?.[0]){storefrontDesign=Object.assign(storefrontDesign,rows[0]);window.storefrontDesign=storefrontDesign}applyStorefrontDesign();fillDesignEditor()}catch(e){console.error('storefront design',e)}}
function applyStorefrontDesign(){document.documentElement.style.setProperty('--store-primary',storefrontDesign.primary_color||'#2563eb');document.documentElement.style.setProperty('--store-accent',storefrontDesign.accent_color||'#16a34a');let title=$('storeBrandName');if(title)title.textContent=storefrontDesign.store_name||'מערכת מכירה';let sw=$('storeSearchWrap');if(sw)sw.classList.toggle('hidden',storefrontDesign.show_search===false);document.body.dataset.bannerStyle=storefrontDesign.banner_style||'soft'}
function cartSnapshot(){let count=0,total=0;Object.values(cart||{}).forEach(x=>{let q=Number(x?.qty||0);count+=q;total+=q*Number(x?.price||0)});return{count,total}}
function updateCartHeader(){let s=cartSnapshot();if($('count'))$('count').textContent=s.count;if($('headTotal'))$('headTotal').textContent=money(s.total);if($('bottomTotal'))$('bottomTotal').textContent=money(s.total);let bc=$('modernBottomCart');if(bc){bc.querySelector('.modern-cart-count').textContent=s.count+' פריטים';bc.querySelector('.modern-cart-total').textContent=money(s.total)+' ₪';bc.classList.toggle('empty',s.count===0)}}
function renderStoreSearch(){let q=String($('storeSearch')?.value||'').trim().toLowerCase();if(!q){renderCats();return}let grid=$('categories');if(!grid)return;let found=activeProducts().filter(p=>p.name.toLowerCase().includes(q));grid.innerHTML='';grid.className='products-grid search-results';found.forEach(p=>{let d=document.createElement('div');d.className='product modern-product';let stock=Number(p.stock_quantity||0),stockText=stock<=0?'אזל מהמלאי':(storefrontDesign.low_stock_message&&stock<=Number(p.low_stock_threshold||3)?'נשארו אחרונים':'');d.innerHTML='<div class="product-imgbox">'+(p.image_url?'<img src="'+esc(p.image_url)+'">':'<div class="product-placeholder">🛍️</div>')+'</div><h3>'+esc(p.name)+'</h3><div class="price">'+money(p.price)+' ₪</div>'+(stockText?'<div class="customer-stock '+(stock<=0?'out':'low')+'">'+stockText+'</div>':'')+'<div class="inline-cart" data-product="'+p.id+'"></div>';grid.appendChild(d);renderInlineCartFor(p.id)});if(!found.length)grid.innerHTML='<div class="card empty-search">לא נמצאו מוצרים</div>'}
function clearStoreSearch(){if($('storeSearch'))$('storeSearch').value='';let grid=$('categories');if(grid)grid.className='categories-grid';renderCats()}
function renderInlineCartFor(id){document.querySelectorAll('.inline-cart[data-product="'+id+'"]').forEach(el=>{let p=activeProducts().find(x=>x.id===id),item=cart[id],qty=Number(item?.qty||0);if(!p)return;if(qty<=0)el.innerHTML='<button class="modern-add" '+(Number(p.stock_quantity||0)<=0?'disabled':'')+' onclick="modernAdd(\''+id+'\')">+ הוסף</button>';else el.innerHTML='<div class="qty-control"><button onclick="modernQty(\''+id+'\',-1)">−</button><b>'+qty+'</b><button onclick="modernQty(\''+id+'\',1)">+</button></div>'})}
function modernAdd(id){let p=activeProducts().find(x=>x.id===id);if(!p)return;addCart(p);renderInlineCartFor(id);updateCartHeader();pulseCart()}
function modernQty(id,delta){let p=activeProducts().find(x=>x.id===id);if(!p)return;let item=cart[id];if(!item&&delta>0)item=cart[id]={...p,qty:0};if(!item)return;let n=Math.max(0,Math.min(Number(p.stock_quantity||0),Number(item.qty||0)+delta));if(n)item.qty=n;else delete cart[id];totals();renderInlineCartFor(id);updateCartHeader();pulseCart()}
function enhanceCartBar(){if($('modernBottomCart')){updateCartHeader();return}let old=document.querySelector('.bottom');if(old)old.classList.add('legacy-bottom');let bar=document.createElement('div');bar.id='modernBottomCart';bar.className='modern-bottom-cart empty';bar.onclick=()=>show('cart');bar.innerHTML='<span class="modern-cart-count">0 פריטים</span><b class="modern-cart-total">0.00 ₪</b><button type="button">לסל ולתשלום ←</button>';document.body.appendChild(bar);let oldTotals=window.totals;window.totals=function(){let r=oldTotals.apply(this,arguments);updateCartHeader();return r};let oldRenderCart=window.renderCart;window.renderCart=function(){let r=oldRenderCart.apply(this,arguments);updateCartHeader();return r};updateCartHeader()}
function pulseCart(){let el=$('modernBottomCart');if(!el)return;el.classList.remove('cart-pulse');void el.offsetWidth;el.classList.add('cart-pulse')}
function ensureDesignAdmin(){let admin=$('admin');if(!admin||$('designTab'))return;let menu=admin.querySelector('.adminmenu');let b=document.createElement('button');b.className='blue';b.textContent='עיצוב החנות';b.onclick=()=>adminTab('designTab');menu?.appendChild(b);let tab=document.createElement('div');tab.id='designTab';tab.className='adminTab hidden';tab.innerHTML='<div class="card form design-editor"><h3>עיצוב החנות ללקוחות</h3><label>שם החנות</label><input id="designStoreName"><div class="design-colors"><div><label>צבע ראשי</label><input id="designPrimary" type="color"></div><div><label>צבע פעולה / תשלום</label><input id="designAccent" type="color"></div></div><label>סגנון מודעות</label><select id="designBanner"><option value="soft">נקי ועדין</option><option value="strong">בולט</option><option value="minimal">מינימלי</option></select><label><input id="designSearch" type="checkbox" style="width:auto"> הצג חיפוש מוצרים</label><label><input id="designLowStock" type="checkbox" style="width:auto"> הצג ללקוח הודעת מלאי נמוך</label><label>מייל לקבלת הערות לקוחות</label><input id="designFeedbackEmail" type="email" placeholder="name@example.com"><div class="msg">לכתובת זו יישלחו בקשות על מוצרים חסרים והערות מהמסך הראשי.</div><button class="green" onclick="saveStorefrontDesign()">שמור עיצוב והגדרות</button></div>';admin.appendChild(tab)}
function fillDesignEditor(){if(!$('designStoreName'))return;$('designStoreName').value=storefrontDesign.store_name||'';$('designPrimary').value=storefrontDesign.primary_color||'#2563eb';$('designAccent').value=storefrontDesign.accent_color||'#16a34a';$('designBanner').value=storefrontDesign.banner_style||'soft';$('designSearch').checked=storefrontDesign.show_search!==false;$('designLowStock').checked=storefrontDesign.low_stock_message!==false;$('designFeedbackEmail').value=storefrontDesign.feedback_email||''}
async function saveStorefrontDesign(){try{let v={store_name:$('designStoreName').value.trim()||'מערכת מכירה',primary_color:$('designPrimary').value,accent_color:$('designAccent').value,banner_style:$('designBanner').value,show_search:$('designSearch').checked,low_stock_message:$('designLowStock').checked,feedback_email:$('designFeedbackEmail').value.trim()||null,updated_at:new Date().toISOString()};await req('/rest/v1/storefront_design_settings?id=eq.1',{method:'PATCH',body:JSON.stringify(v)});storefrontDesign=Object.assign(storefrontDesign,v);window.storefrontDesign=storefrontDesign;applyStorefrontDesign();alert('העיצוב וההגדרות נשמרו')}catch(e){alert('שמירת ההגדרות נכשלה: '+e.message)}}
window.addEventListener('load',ensureStorefrontModernUI);