from pathlib import Path
p=Path('app/src/main/java/com/simplestore/tablet/MainActivity.java')
s=p.read_text(encoding='utf-8')
old='''        Button save=button("שמור והפחת מהמלאי",green,Color.WHITE);save.setOnClickListener(v->{Product p=findProductByNameNative(product.getText().toString());if(p==null){Toast.makeText(this,"יש לבחור מוצר קיים",Toast.LENGTH_LONG).show();return;}int q;try{q=Integer.parseInt(qty.getText().toString().trim());}catch(Exception e){q=0;}if(q<=0){Toast.makeText(this,"כמות לא תקינה",Toast.LENGTH_LONG).show();return;}final int fq=q;io.execute(()->{try{double[] cs=loadNativeCostAndStock(p.id);double total=cs[0]*fq;if(fq>cs[1]){main.post(()->Toast.makeText(this,"אין מספיק מלאי",Toast.LENGTH_LONG).show());return;}main.post(()->new AlertDialog.Builder(this).setTitle("אישור שימוש עצמי").setMessage("להפחית "+p.name+" × "+fq+" מהמלאי?\\nסה״כ לפי עלות: "+String.format(Locale.ROOT,"%.2f",total)+" ₪").setNegativeButton("ביטול",null).setPositiveButton("שמור",(d,w)->saveHomeUseNative(p,fq,note.getText().toString())).show());}catch(Exception e){main.post(()->Toast.makeText(this,"טעינת פרטי המוצר נכשלה: "+safeMsg(e),Toast.LENGTH_LONG).show());}});});content.addView(save,new LinearLayout.LayoutParams(-1,dp(60)));
    }

    private void saveHomeUseNative(Product p,int qty,String note){
        io.execute(()->{try{JSONObject item=new JSONObject();item.put("product_id",p.id);item.put("quantity",qty);JSONArray items=new JSONArray();items.put(item);JSONObject body=new JSONObject();body.put("p_items",items);body.put("p_note",note==null||note.trim().isEmpty()?JSONObject.NULL:note.trim());body.put("p_taken_at",new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssXXX",Locale.ROOT).format(new Date()));requestRaw("POST","/rest/v1/rpc/create_home_withdrawal",body,true);loadData(()->{Toast.makeText(this,"נשמר והמלאי עודכן",Toast.LENGTH_LONG).show();showHomeUseNative();});}catch(Exception e){main.post(()->Toast.makeText(this,"שמירת שימוש עצמי נכשלה: "+safeMsg(e),Toast.LENGTH_LONG).show());}});
    }'''
new='''        View.OnClickListener saveAction=v->{boolean deduct=v.getId()!=987654;Product p=findProductByNameNative(product.getText().toString());if(p==null){Toast.makeText(this,"יש לבחור מוצר קיים",Toast.LENGTH_LONG).show();return;}int q;try{q=Integer.parseInt(qty.getText().toString().trim());}catch(Exception e){q=0;}if(q<=0){Toast.makeText(this,"כמות לא תקינה",Toast.LENGTH_LONG).show();return;}final int fq=q;io.execute(()->{try{double[] cs=loadNativeCostAndStock(p.id);double total=cs[0]*fq;if(deduct&&fq>cs[1]){main.post(()->Toast.makeText(this,"אין מספיק מלאי",Toast.LENGTH_LONG).show());return;}String msg=deduct?"להפחית "+p.name+" × "+fq+" מהמלאי?":"לשמור "+p.name+" × "+fq+" ללא שינוי במלאי?";main.post(()->new AlertDialog.Builder(this).setTitle("אישור שימוש עצמי").setMessage(msg+"\\nסה״כ לפי עלות: "+String.format(Locale.ROOT,"%.2f",total)+" ₪").setNegativeButton("ביטול",null).setPositiveButton("שמור",(d,w)->saveHomeUseNative(p,fq,note.getText().toString(),deduct)).show());}catch(Exception e){main.post(()->Toast.makeText(this,"טעינת פרטי המוצר נכשלה: "+safeMsg(e),Toast.LENGTH_LONG).show());}});};
        Button save=button("שמור והפחת מהמלאי",green,Color.WHITE);save.setOnClickListener(saveAction);content.addView(save,new LinearLayout.LayoutParams(-1,dp(60)));
        Button saveOnly=button("שמור בלבד — ללא הפחתה מהמלאי",Color.WHITE,blue);saveOnly.setId(987654);saveOnly.setOnClickListener(saveAction);LinearLayout.LayoutParams sop=new LinearLayout.LayoutParams(-1,dp(60));sop.setMargins(0,dp(10),0,0);content.addView(saveOnly,sop);
    }

    private void saveHomeUseNative(Product p,int qty,String note,boolean deduct){
        io.execute(()->{try{JSONObject item=new JSONObject();item.put("product_id",p.id);item.put("quantity",qty);JSONArray items=new JSONArray();items.put(item);JSONObject body=new JSONObject();body.put("p_items",items);body.put("p_note",note==null||note.trim().isEmpty()?JSONObject.NULL:note.trim());body.put("p_taken_at",new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssXXX",Locale.ROOT).format(new Date()));body.put("p_deduct_stock",deduct);requestRaw("POST","/rest/v1/rpc/create_home_withdrawal",body,true);loadData(()->{Toast.makeText(this,deduct?"נשמר והמלאי עודכן":"נשמר ללא שינוי במלאי",Toast.LENGTH_LONG).show();showHomeUseNative();});}catch(Exception e){main.post(()->Toast.makeText(this,"שמירת שימוש עצמי נכשלה: "+safeMsg(e),Toast.LENGTH_LONG).show());}});
    }'''
if old not in s: raise SystemExit('home use block not found')
s=s.replace(old,new,1)
s=s.replace('רישום מוצרים שנלקחו לשימוש עצמי. השמירה מפחיתה מהמלאי ומחשבת לפי מחיר העלות.','רישום מוצרים שנלקחו לשימוש עצמי. אפשר לשמור עם הפחתה מהמלאי או ללא הפחתה. המחיר מחושב לפי העלות.',1)
p.write_text(s,encoding='utf-8')
print('android home save mode applied')
