from pathlib import Path

p=Path('android/app/src/main/java/com/simplestore/tablet/MainActivity.java')
s=p.read_text(encoding='utf-8')

s=s.replace('offline.watchConnection(()->main.post(this::offerPendingSync));','offline.watchConnection(()->main.post(this::startAutomaticSync));')

start=s.index('    private void offerPendingSync(){')
end=s.index('    private String requestRaw(', start)
replacement='''    private volatile boolean automaticSyncRunning = false;\n    private int automaticSyncRetry = 0;\n\n    private void offerPendingSync(){ startAutomaticSync(); }\n\n    private void startAutomaticSync(){\n        if(offline==null||!offline.isOnline()||offline.pendingCount()==0||automaticSyncRunning)return;\n        automaticSyncRunning=true;\n        syncPendingOperations();\n    }\n\n    private void scheduleSyncRetry(){\n        automaticSyncRunning=false;\n        if(offline==null||!offline.isOnline()||offline.pendingCount()==0)return;\n        automaticSyncRetry=Math.min(automaticSyncRetry+1,6);\n        long delay=Math.min(60000L,2000L*(1L<<Math.min(automaticSyncRetry,5)));\n        main.postDelayed(this::startAutomaticSync,delay);\n    }\n\n    private void syncPendingOperations(){\n        io.execute(()->{\n            JSONArray queue=offline.pending(),remaining=new JSONArray();int completed=0;\n            for(int i=0;i<queue.length();i++){\n                JSONObject op=queue.optJSONObject(i);if(op==null)continue;\n                try{\n                    requestRaw(op.optString("method"),op.optString("path"),op.optJSONObject("body"),op.optBoolean("admin",true));\n                    completed++;\n                }catch(Exception e){\n                    try{\n                        JSONObject failedOp=new JSONObject(op.toString());\n                        String reason=e.getMessage();\n                        if(reason==null||reason.trim().isEmpty())reason=e.getClass().getSimpleName();\n                        failedOp.put("last_error",reason);\n                        failedOp.put("last_attempt_at",System.currentTimeMillis());\n                        remaining.put(failedOp);\n                    }catch(Exception ignored){remaining.put(op);}\n                }\n            }\n            offline.replacePending(remaining);\n            if(completed>0)offline.markSynced();\n            int synced=completed,left=offline.pendingCount(),failed=offline.failedCount();\n            automaticSyncRunning=false;\n            if(left==0)automaticSyncRetry=0;\n            main.post(()->{\n                if(synced>0)Toast.makeText(this,left==0?"הסנכרון הושלם: "+synced+" שינויים הועלו":"הועלו "+synced+" שינויים · "+left+" עדיין ממתינים",Toast.LENGTH_LONG).show();\n                if(failed>0)Toast.makeText(this,failed+" פעולות הופרדו בגלל שגיאת סנכרון",Toast.LENGTH_LONG).show();\n                if(left>0)scheduleSyncRetry();\n            });\n        });\n    }\n\n'''
s=s[:start]+replacement+s[end:]

old='''        int pending=offline==null?0:offline.pendingCount();\n        if((offline!=null&&!offline.isOnline())||pending>0){\n            String status=!offline.isOnline()?"אין אינטרנט":"מחובר";\n            if(pending>0)status+=" · "+pending+" שינויים ממתינים לסנכרון";\n            TextView offlineStatus=text(status,14,true);offlineStatus.setTextColor(pending>0?red:blue);offlineStatus.setPadding(dp(16),dp(7),dp(16),dp(7));root.addView(offlineStatus);\n        }'''
new='''        int pending=offline==null?0:offline.pendingCount();\n        int failed=offline==null?0:offline.failedCount();\n        long lastSync=offline==null?0:offline.lastSync();\n        if(offline!=null&&(!offline.isOnline()||pending>0||failed>0)){\n            String status=!offline.isOnline()?"אין אינטרנט · אפשר להמשיך לעבוד":"מחובר";\n            if(pending>0)status+=" · "+pending+" שינויים ממתינים לסנכרון";\n            if(failed>0)status+=" · "+failed+" פעולות עם שגיאה";\n            if(lastSync>0)status+=" · סנכרון אחרון "+new SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date(lastSync));\n            TextView offlineStatus=text(status,14,true);offlineStatus.setTextColor((pending>0||failed>0)?red:blue);offlineStatus.setPadding(dp(16),dp(7),dp(16),dp(7));root.addView(offlineStatus);\n        }'''
if old not in s:
    raise SystemExit('buildShell offline status block not found')
s=s.replace(old,new,1)

p.write_text(s,encoding='utf-8')
print('Applied automatic offline sync, retry, exact failure reasons and status UI')
