from pathlib import Path
p=Path('android/app/src/main/java/com/simplestore/tablet/MainActivity.java')
s=p.read_text(encoding='utf-8')
needle='''        Button countInventory=button("ספירת מלאי",Color.WHITE,blue);countInventory.setOnClickListener(v->showInventoryCount());LinearLayout.LayoutParams countParams=new LinearLayout.LayoutParams(-1,dp(64));countParams.setMargins(0,0,0,dp(12));content.addView(countInventory,countParams);'''
insert=needle+'''\n        Button syncStatus=button("מצב סנכרון",Color.WHITE,blue);syncStatus.setOnClickListener(v->showSyncStatus());LinearLayout.LayoutParams syncParams=new LinearLayout.LayoutParams(-1,dp(64));syncParams.setMargins(0,0,0,dp(12));content.addView(syncStatus,syncParams);'''
if needle not in s: raise SystemExit('admin inventory button anchor not found')
s=s.replace(needle,insert,1)
anchor='''    private void showProductsAdmin(){'''
method='''    private void showSyncStatus(){\n        buildShell("מצב סנכרון",this::showAdminHome,false);\n        int pending=offline==null?0:offline.pendingCount(),failed=offline==null?0:offline.failedCount();\n        long last=offline==null?0:offline.lastSync();\n        String lastText=last>0?new SimpleDateFormat("dd/MM/yyyy HH:mm",Locale.getDefault()).format(new Date(last)):"עדיין לא בוצע";\n        LinearLayout info=card();\n        TextView title=text((offline!=null&&offline.isOnline()?"מחובר לאינטרנט":"אין אינטרנט"),22,true);title.setTextColor(offline!=null&&offline.isOnline()?green:red);info.addView(title);\n        info.addView(text("שינויים שממתינים: "+pending,18,true));\n        info.addView(text("פעולות עם שגיאה: "+failed,18,true));\n        info.addView(text("סנכרון אחרון: "+lastText,16,false));content.addView(info);\n        Button refresh=button("רענן מצב",Color.WHITE,blue);refresh.setOnClickListener(v->showSyncStatus());LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(54));rp.setMargins(0,dp(8),0,dp(8));content.addView(refresh,rp);\n        if(pending>0){Button sync=button("סנכרן עכשיו",blue,Color.WHITE);sync.setEnabled(offline!=null&&offline.isOnline());sync.setOnClickListener(v->{startAutomaticSync();Toast.makeText(this,"הסנכרון הופעל",Toast.LENGTH_SHORT).show();main.postDelayed(this::showSyncStatus,1800);});LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(58));sp.setMargins(0,dp(10),0,dp(10));content.addView(sync,sp);}\n        if(failed>0){\n            JSONArray bad=offline.failed();\n            TextView h=text("בעיות סנכרון",20,true);h.setPadding(0,dp(14),0,dp(8));content.addView(h);\n            for(int i=0;i<bad.length();i++){JSONObject op=bad.optJSONObject(i);if(op==null)continue;String method=op.optString("method"),path=op.optString("path"),reason=op.optString("last_error","");long when=op.optLong("failed_at",0);String time=when>0?new SimpleDateFormat("dd/MM HH:mm",Locale.getDefault()).format(new Date(when)):"";LinearLayout row=card();row.addView(text(method+"  "+path,15,true));row.addView(text("נכשל לאחר מספר ניסיונות"+(time.isEmpty()?"":" · "+time),14,false));if(!reason.isEmpty()){TextView err=text("סיבה: "+reason,14,false);err.setTextColor(red);row.addView(err);}content.addView(row);}\n            Button retry=button("נסה שוב את הפעולות שנכשלו",green,Color.WHITE);retry.setEnabled(offline.isOnline());retry.setOnClickListener(v->{offline.retryFailed();startAutomaticSync();Toast.makeText(this,"הפעולות הוחזרו לסנכרון",Toast.LENGTH_LONG).show();main.postDelayed(this::showSyncStatus,1800);});content.addView(retry,new LinearLayout.LayoutParams(-1,dp(60)));\n        }\n    }\n\n'''
if anchor not in s: raise SystemExit('showProductsAdmin anchor not found')
s=s.replace(anchor,method+anchor,1)
p.write_text(s,encoding='utf-8')
print('Added sync status admin screen with exact errors and refresh')
