package com.simplestore.tablet;

import android.content.Context;
import android.content.SharedPreferences;
import android.net.ConnectivityManager;
import android.net.Network;
import android.net.NetworkCapabilities;
import android.net.NetworkRequest;
import org.json.JSONArray;
import org.json.JSONObject;
import java.util.UUID;

final class OfflineStore {
    private static final String PREFS="simple_store_offline",CATEGORIES="categories",PRODUCTS="products",SUPPLIERS="suppliers",QUEUE="pending_operations",FAILED="failed_operations",LAST_SYNC="last_sync",LAST_FAILED_ID="last_failed_id",FAIL_COUNT="fail_count";
    private final Context context; private final SharedPreferences prefs;
    OfflineStore(Context context){this.context=context.getApplicationContext();this.prefs=this.context.getSharedPreferences(PREFS,Context.MODE_PRIVATE);}
    boolean isOnline(){try{ConnectivityManager cm=(ConnectivityManager)context.getSystemService(Context.CONNECTIVITY_SERVICE);Network n=cm.getActiveNetwork();if(n==null)return false;NetworkCapabilities c=cm.getNetworkCapabilities(n);return c!=null&&c.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)&&(c.hasTransport(NetworkCapabilities.TRANSPORT_WIFI)||c.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR)||c.hasTransport(NetworkCapabilities.TRANSPORT_ETHERNET)||c.hasTransport(NetworkCapabilities.TRANSPORT_VPN));}catch(Exception e){return false;}}
    void watchConnection(Runnable onConnected){try{ConnectivityManager cm=(ConnectivityManager)context.getSystemService(Context.CONNECTIVITY_SERVICE);NetworkRequest r=new NetworkRequest.Builder().addCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET).build();cm.registerNetworkCallback(r,new ConnectivityManager.NetworkCallback(){@Override public void onAvailable(Network n){onConnected.run();}@Override public void onCapabilitiesChanged(Network n,NetworkCapabilities c){if(c.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET))onConnected.run();}});}catch(Exception ignored){}}
    synchronized void saveCatalog(JSONArray c,JSONArray p){prefs.edit().putString(CATEGORIES,c.toString()).putString(PRODUCTS,p.toString()).apply();}
    synchronized JSONArray categories(){return read(CATEGORIES);} synchronized JSONArray products(){return read(PRODUCTS);} synchronized void saveSuppliers(JSONArray s){prefs.edit().putString(SUPPLIERS,s.toString()).apply();} synchronized JSONArray suppliers(){return read(SUPPLIERS);}
    synchronized int pendingCount(){return read(QUEUE).length();} synchronized int failedCount(){return read(FAILED).length();} synchronized JSONArray failed(){return read(FAILED);}
    synchronized void retryFailed(){JSONArray bad=read(FAILED),q=read(QUEUE);for(int i=0;i<bad.length();i++){JSONObject x=bad.optJSONObject(i);if(x==null)continue;x.remove("failed_at");x.remove("failure_count");x.remove("last_error");q.put(x);}prefs.edit().putString(QUEUE,q.toString()).putString(FAILED,"[]").remove(LAST_FAILED_ID).remove(FAIL_COUNT).commit();}
    synchronized void clearFailed(){prefs.edit().putString(FAILED,"[]").commit();}
    synchronized JSONArray pending(){JSONArray q=read(QUEUE);if(q.length()<2)return q;JSONArray rotated=new JSONArray();for(int i=1;i<q.length();i++)rotated.put(q.opt(i));rotated.put(q.opt(0));return rotated;}
    synchronized void replacePending(JSONArray v){try{if(v!=null&&v.length()>0){JSONObject first=v.optJSONObject(0);String id=first==null?"":first.optString("id","");String old=prefs.getString(LAST_FAILED_ID,"");int count=id.equals(old)?prefs.getInt(FAIL_COUNT,0)+1:1;if(!id.isEmpty()&&count>=3){JSONArray bad=read(FAILED);JSONObject copy=new JSONObject(first.toString());copy.put("failed_at",System.currentTimeMillis());copy.put("failure_count",count);bad.put(copy);JSONArray keep=new JSONArray();for(int i=1;i<v.length();i++)keep.put(v.opt(i));prefs.edit().putString(FAILED,bad.toString()).putString(QUEUE,keep.toString()).remove(LAST_FAILED_ID).remove(FAIL_COUNT).commit();return;}prefs.edit().putString(LAST_FAILED_ID,id).putInt(FAIL_COUNT,count).putString(QUEUE,v.toString()).commit();return;}}catch(Exception ignored){}prefs.edit().putString(QUEUE,v==null?"[]":v.toString()).remove(LAST_FAILED_ID).remove(FAIL_COUNT).commit();}
    synchronized void markSynced(){prefs.edit().putLong(LAST_SYNC,System.currentTimeMillis()).apply();} synchronized long lastSync(){return prefs.getLong(LAST_SYNC,0);}
    synchronized JSONObject enqueue(String method,String path,JSONObject originalBody,boolean admin)throws Exception{JSONObject body=originalBody==null?new JSONObject():new JSONObject(originalBody.toString());if("POST".equals(method)&&(path.startsWith("/rest/v1/products")||path.startsWith("/rest/v1/categories")||path.startsWith("/rest/v1/suppliers"))&&!body.has("id"))body.put("id",UUID.randomUUID().toString());JSONObject op=new JSONObject();op.put("id",UUID.randomUUID().toString());op.put("method",method);op.put("path",path);op.put("body",body);op.put("admin",admin);op.put("created_at",System.currentTimeMillis());JSONArray q=read(QUEUE);q.put(op);replacePending(q);apply(method,path,body);return body;}
    private void apply(String method,String path,JSONObject body)throws Exception{if(path.startsWith("/rest/v1/products")){JSONArray r=read(PRODUCTS);if("POST".equals(method))r.put(new JSONObject(body.toString()));else if("DELETE".equals(method))removeByQuery(r,path);else patchByQuery(r,path,body);prefs.edit().putString(PRODUCTS,r.toString()).commit();}else if(path.startsWith("/rest/v1/categories")){JSONArray r=read(CATEGORIES);if("POST".equals(method))r.put(new JSONObject(body.toString()));else if("DELETE".equals(method))removeByQuery(r,path);else patchByQuery(r,path,body);prefs.edit().putString(CATEGORIES,r.toString()).commit();}else if(path.startsWith("/rest/v1/suppliers")){JSONArray r=read(SUPPLIERS);if("POST".equals(method))r.put(new JSONObject(body.toString()));else if("DELETE".equals(method))removeByQuery(r,path);else patchByQuery(r,path,body);prefs.edit().putString(SUPPLIERS,r.toString()).commit();}else if(path.contains("/rpc/adjust_stock")){JSONArray r=read(PRODUCTS);String id=body.optString("p_product_id");int ch=body.optInt("p_change_qty");for(int i=0;i<r.length();i++){JSONObject x=r.getJSONObject(i);if(id.equals(x.optString("id")))x.put("stock_quantity",x.optInt("stock_quantity")+ch);}prefs.edit().putString(PRODUCTS,r.toString()).commit();}else if(path.contains("/rpc/archive_product")){JSONArray r=read(PRODUCTS);removeById(r,body.optString("p_product_id"));prefs.edit().putString(PRODUCTS,r.toString()).commit();}else if(path.contains("/rpc/create_purchase")){JSONArray r=read(PRODUCTS),items=body.optJSONArray("p_items");if(items!=null)for(int j=0;j<items.length();j++){JSONObject it=items.getJSONObject(j);String id=it.optString("product_id");for(int i=0;i<r.length();i++){JSONObject x=r.getJSONObject(i);if(id.equals(x.optString("id"))){x.put("stock_quantity",x.optInt("stock_quantity")+it.optInt("quantity"));if(it.has("sale_price"))x.put("price",it.optDouble("sale_price"));}}}prefs.edit().putString(PRODUCTS,r.toString()).commit();}}
    private void patchByQuery(JSONArray r,String path,JSONObject b)throws Exception{String id=queryId(path);for(int i=0;i<r.length();i++){JSONObject x=r.getJSONObject(i);if(id.equals(x.optString("id"))){JSONArray n=b.names();if(n!=null)for(int j=0;j<n.length();j++){String k=n.getString(j);x.put(k,b.get(k));}}}} private void removeByQuery(JSONArray r,String p)throws Exception{removeById(r,queryId(p));} private void removeById(JSONArray r,String id)throws Exception{for(int i=r.length()-1;i>=0;i--)if(id.equals(r.getJSONObject(i).optString("id")))r.remove(i);} private String queryId(String p){int i=p.indexOf("id=eq.");if(i<0)return"";String s=p.substring(i+6);int a=s.indexOf('&');return a<0?s:s.substring(0,a);} private JSONArray read(String k){try{return new JSONArray(prefs.getString(k,"[]"));}catch(Exception e){return new JSONArray();}}
}
