plugins {
    id 'com.android.application'
}

android {
    namespace 'com.simplestore.tablet'
    compileSdk 35

    defaultConfig {
        applicationId 'com.simplestore.tablet'
        minSdk 23
        targetSdk 35
        versionCode = Integer.parseInt((project.findProperty('versionCode') ?: '1').toString())
        versionName = (project.findProperty('versionName') ?: '1.0').toString()
    }
}
