plugins {
    id 'com.android.application'
}

android {
    namespace 'com.simplestore.tablet'
    compileSdk 35

    defaultConfig {
        applicationId 'com.simplestore.tablet'
        minSdk 23
        targetSdk 35
        versionCode (project.findProperty('versionCode') ?: '1') as Integer
        versionName (project.findProperty('versionName') ?: '1.0')
    }
}
